# Generated by Django 5.0.3 on 2024-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeinfo",
            name="img",
            field=models.ImageField(default=list, upload_to="all_img"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aboutinfo",
            name="image",
            field=models.ImageField(upload_to="all_img"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(upload_to="all_img"),
        ),
        migrations.AlterField(
            model_name="ouerservice",
            name="image",
            field=models.ImageField(upload_to="all_img"),
        ),
        migrations.AlterField(
            model_name="portfo",
            name="img",
            field=models.ImageField(upload_to="all_img"),
        ),
    ]
