# Generated by Django 5.0.3 on 2024-05-18 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_homeinfo_img_alter_aboutinfo_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutinfo",
            old_name="image",
            new_name="about_image",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="image",
            new_name="cust_image",
        ),
        migrations.RenameField(
            model_name="homeinfo",
            old_name="img",
            new_name="home_img",
        ),
        migrations.RenameField(
            model_name="ouerservice",
            old_name="image",
            new_name="ser_image",
        ),
    ]
