# Generated by Django 5.0.3 on 2024-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_delete_homeinfo_delete_portfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutinfo",
            name="about_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="all_img", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cust_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="all_img", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="ouerservice",
            name="ser_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="all_img", verbose_name="Image"
            ),
        ),
    ]
